title: Whirlwind-Theme
keywords: 'Whirlwind Theme'
favicon: /images/default-favicon.ico
logo: /images/default-logo.webp

author: SakuraKooi
description: "It's a minimal but stylish hexo theme!"
copyright: '2024'
moeICP: '114514'

menu:
  - text: 首页
    link: '/'
  - text: 归档
    title: 归档
    link: '/archives'

contacts:
  - icon: 'fa-brands fa-github'
    url: https://github.com/SakuraKoi
  - icon: 'fa-brands fa-twitter'
    url: https://dummy.com/
  - icon: 'fa-brands fa-youtube'
    url: https://dummy.com/
  - icon: 'fa-brands fa-telegram'
    url: https://dummy.com/
  - icon: 'fa-brands fa-google'
    url: https://dummy.com/


gitalk:
  enable: true
  clientId: '114514'
  clientSecret: '114514'
  repo: '114514'
  owner: '114514'
  admin: '114514'

node_sass:
  outputStyle: expanded

syntax_highlighter: prismjs
prismjs:
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ""

encrypt:
  abstract: '受到密码保护的内容w'
  message: '这里有一些受到密码保护的内容, 请输入解密密码'
  wrong_pass_message: '似乎你输入了错误的密码哦~'
  wrong_hash_message: '错误: 数据校验失败, 内容可能已被损坏'