title: Whirlwind-Theme
keywords: SakuraKooi
favicon: /images/favicon.ico
logo: /images/logo.webp

author: SakuraKooi
description: "It's a minimal but stylish hexo theme!"
copyright: '2024'
moeICP: '114514'

menu:
  - title: 首页
    link: '/'
    showOnTitle: false
  - title: 归档
    link: '/archives'
    showOnTitle: true
  - title: 留言
    link: '/guestbook'
    showOnTitle: true
  - title: 友链
    link: '/links'
    showOnTitle: true
  - title: 关于
    link: '/about'
    showOnTitle: true

contacts:
  - icon: 'fa-brands fa-github'
    url: https://github.com/SakuraKoi
  - icon: 'fa-brands fa-twitter'
    url: https://dummy.com/
  - icon: 'fa-brands fa-youtube'
    url: https://dummy.com/
  - icon: 'fa-brands fa-telegram'
    url: https://dummy.com/
  - icon: 'fa-brands fa-google'
    url: https://dummy.com/


gitalk:
  enable: false
  clientId: '114514'
  clientSecret: '114514'
  repo: '114514'
  owner: '114514'
  admin: '114514'